// Generated by CoffeeScript 1.12.5
var autoprefixer, browserSync, gulp, sass, sourcemaps;

gulp = require("gulp");

browserSync = require("browser-sync").create();

sass = require("gulp-sass");

sourcemaps = require("gulp-sourcemaps");

autoprefixer = require("gulp-autoprefixer");

gulp.task("sass", function() {
	return gulp
		.src("scss/*.scss")
		.pipe(sourcemaps.init())
		.pipe(sass())
		.pipe(sourcemaps.write("."))
		.pipe(gulp.dest("."))
		.pipe(browserSync.stream());
});

gulp.task("serve", ["sass"], function() {
	browserSync.init({
		server: "."
	});
	gulp.watch("scss/*.scss", ["sass"]);
	gulp.watch("main.css", ["prefix"]);
	return gulp.watch("index.html").on("change", browserSync.reload);
});

gulp.task("prefix", function() {
	return gulp.src("main.css").pipe(autoprefixer()).pipe(gulp.dest("css"));
});

gulp.task("default", ["serve"]);

//# sourceMappingURL=gulpfile.js.map
